### ISSUE TITLE
Filter highlighting only works up to first linebreak

### ISSUE THREAD

**Issue by olivierlacan** [ezekg/language-haml#44]
@ezekg You asked for feedback and this is the only odd thing I've noticed since the last release (0.22.2):

This `:javascript` filter is highlighted properly:
![image](https://cloud.githubusercontent.com/assets/65950/10047724/76f65d1e-61dd-11e5-93c0-b3348d10c808.png)

While this one isn't:
![image](https://cloud.githubusercontent.com/assets/65950/10047783/c692ba34-61dd-11e5-8f07-a660fb189c94.png)

If I remove the new line between the first `var` declaration and the second, the highlighting turns back on:
![image](https://cloud.githubusercontent.com/assets/65950/10047808/e0845bfa-61dd-11e5-8ff9-df82d90838ff.png)

**Comment by ezekg** [comment]
Thanks. I've had a really tough time with this one. I can't find a good regex for matching a filter's 'end' when the white space gets trimmed. If you left the white space there, it would work fine. But, since it gets trimmed, the regex thinks that the filter has been exited and that the remaining text is plaintext. You can see the issue with the trimmed whitespace below (one has been trimmed, the other hasn't):

![image](https://cloud.githubusercontent.com/assets/6979737/10048303/de64e7e6-61d7-11e5-9f26-c4d2e3696591.png)

If I do it the way it was done before, all text below the filter gets highlighted wrong if there's no newline between the filter and any regular Haml directly following the filter (sometime the highlighting is wrong regardless of whether there's a newline or not, oddly). I chose the lesser of the 2 evils for now, because having an entire file with broken syntax highlighting isn't fun.

Maybe there's a way to track the amount of indentation and only exit when that goes below a certain threshold, but I'm not entirely sure that's possible with just a couple regexes.

**Comment by olivierlacan** [comment]
I knew my pedantic whitespace trimming ways would one day come to bite me again. :-)

This is really a tricky one. I'll ask people more familiar with fancy regex.

**Comment by ezekg** [comment]
Let me know if you figure anything out. I've tried multiple ways, but nothing seems to handle every edge case.

**Comment by ezekg** [comment]
You would have to be able to handle cases like this:
```haml
- some_ruby do
  :coffee
    class Klass
      
      constructor: () ->
        do someFunc
        # ...
  Some plain text here...
  - some_more_ruby do
    :coffee
      do something -> @.somethingElse()
      # ...
  = and_more_ruby "here"
```

As you can see, I think Github's syntax highlighting handles this the same way I'm currently handling it.

**Comment by ezekg** [comment]
Figured it out. Let me know if you find any issues. :+1:

**Comment by olivierlacan** [comment]
Nice! Checking it out :-)

**Comment by olivierlacan** [comment]
Fix confirmed, great work @ezekg! :-0

**Comment by ezekg** [comment]
Boom! 0 open issues.

(•_•)
( •_•)>⌐■-■
(⌐■_■)
