### ISSUE TITLE
Can't comment javascript in :javascript sections

### ISSUE THREAD

**Issue by lewisinc** [ezekg/language-haml#66]
Not sure what technical limitations you're working with, but attempting to comment javascript using cmd-/ instead prepends the usual `-#` instead of `//` to that line. Is this fixable or are you limited to having a single commenting style per filetype?

**Comment by ezekg** [comment]
Yeah, this issue has always bugged me. I think it's because the [comment scopes](https://github.com/ezekg/language-haml/blob/master/settings/language-haml.cson) are set to `.text.{LANG}` (in our case `LANG = haml`), while the embedded scopes (what the filters are defined as) is `.meta.embedded.{LANG}` _inside_ of the `.text.haml` scope, so it always uses Haml comments. I'll try and dig in soon and see if there's a way I can fix it. Feel free to dig in yourself if you have time!
